export const INPUT_CHANGED = 'INPUT_CHANGED';
export const SET_USERNAMES = 'SET_USERNAMES';
export const SET_ERROR = 'SET_ERROR';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_ACTIVE_REPOS_DETAILS = 'SET_ACTIVE_REPOS_DETAILS';